# %%

WORKSPACE = "/media/tao/disk4T/jason/transformers"

# %% [markdown]

"""
[1.5.3] OthelloGPT

# Introduction

Note - unless otherwise specified, first person here
refers to the primary researcher, Neel Nanda.

Emergent World Representations is a fascinating
recent ICLR Oral paper from Kenneth Li et al,
summarised in Kenneth's excellent post on the Gradient.
They trained a model (Othello-GPT) to play legal
moves in the board game Othello, by giving it random
games (generated by choosing a legal next move
uniformly at random) and training it to
predict the next move. The headline result is that
Othello-GPT learns an emergent world representation -
despite never being explicitly given the state of the
board, and just being tasked to predict the next move,
it learns to compute the state of the board at each move.
(Note that the point of Othello-GPT is to play
legal moves, not good moves, though they also study a
model trained to play good moves.)

They present two main pieces of evidence. They
can extract the board state from the model's residual
stream via non-linear probes (a two layer ReLU)
MLP). And they can use the probes to causally
intervene and change the model representation's of
the board (by using gradient descent to have the
probes output the new board state) - the model
now makes legal moves in the new board state
even if they are not legal in the old board, and
even if that board state is impossible to reach
by legal play!

I've strengthened their headline result by
finding that much of their more sophisticated (and thus
potentially misleading) techniques can be
significantly simplified. Not only does the model
learn an emergent world representation, it learns
a linear emergent world represnetation, which
can be causally intervened on in a linear way!

But rather than representing "this square has a black/
white piece", it represents "this square has my/their
piece". The model plays both black and white moves,
so this is far more natural from its perspective.
With this insight, the whole picture clarifies
significantly, and the model becomes far more
interpretable!

# The research process

You can read more about the research process in this post here,
which we'd strongly recommend. The exercises are
structured in a different way to the chronological
research process (e.g. we look at probes early on,
when actually training a probe is a high-effort thing
and if you were trying to get traction
on a problem like this you'd want to use more
basic techniques first, like logit lens / attention
pattern analysis).

As you're going through these exercises, we encourage
you to keep thinking about how you would approach
this research process. Do any of the results /
approaches seem completely out of the blue for you,
and if so can you think about what the justification
might have been for trying them? What would
you have tried first, and why?

# How you should approach these exercises

There's a lot of setup code for analysing OthelloGPT
(this is somewhat unavoidable). There are also a lot
of different plots of tensors with different
dimensions and different meanings, and it can be
hard to keep track of. You don't have to keep
track of all this in your head, but we strongly
recommend explaining to yourself or your pair
programming partner what the significance of each
result is before you move on to the next section.
Some times exercises and questions will prompt you
to do this, but you should make it a reflex!

At the end of each subsection in the first section
(which mostly consists of setup), there's a recap of all
the objects we've defined, why they matter, and how
they can be used. There will also be a "recap of
this section" at the end of each of the later sections,
where we review the key results and their significance.

# The purpose / structure of these exercises

At a surface level, these exercises are designed
to help you understand the OthelloGPT model and the
forms of probing & analysis that were done on it. But
it's also designed to make you a better interpretability
researcher! As a result, most exercises will be
doing a combination of:
1. Showing you some new feature/component of OthelloGPT, and
2. Teaching you how to use tools and interpret results
in a broader mech interp context.

As you're going through these exercises, it's
easy to get lost in the fiddly details of the
techniques you're implementing or the things you're
computing. Make sure you keep taking a high-level view,
asking yourself what questions you're currently
trying to ask and how you'll interpret the output you're
getting, as well as how the tools you're currently
using are helping guide you toward a better understanding
of the model

# Content & Learning Objectives

[1] Model Setup & Linear PRobes

In this section, we'll set up the model that we'll
use for the rest of the exercises, and load in weights.
We'll also get familiar with the datasets and objects
that we'll be using for this analysis. Lastly,
we'll learn about linear probes and how they are used

Learning Objectives
- Understand the basic structure of the Othello-GPT model
- Become familiar with the basic tools we'll use for
board visualization during these exercises
- See how our linear probe works, and how we can change
basis between "black/white piece" and "mine/their piece"
- Intervene with the linear probe to influence model predictions

[2] Looking for modular circuits

Here, we'll use our probe to start to analyse
circuits in our model. We can apply them to our
neurons' output weights to identify which neurons
matter and in what way, and we can also figure out when and
where information is represented in a model.

# Learning Objectives
- Learn how to use our linear probe across mutliple layers
- Apply activation patching at a given sequence position
to test hypotheses about our model
- Understand how a neuron can be characterized in terms
of its input and output weights

[3] Neuron Interpretability: A Deep Dive
To practice neuron interpretability, we'll take
a deep dive into understanding one particular neuron -
the techniques and code should transfer pretty well
to any other neurons

The spirit of this section is to practice doing
various standard things that you could go and apply
to another neuron in practice - I end it still being
fairly confused, and with many dangling threads

Learning Objectives
- Apply direct logit attribution to understand
how a neuron's output weights directly effect
predictions
- Use SVD-based techniques to assess how
much of a neuron's input/output behaviour is
captured by some subspace
- Use techniques like max activating datasets and
spectrum plots, and understand their strengths
and limitations

[4] Training a Probe
In this section, we'll look at how to actually train
our linear probe. This section is less mechanistic
interpretability and more standard ML techniques,
but it's still important to understand how to
do this if you want to do any analysis like this
yourself!

Learning Objectives
- Learn how to set up and train a linear probe
- See how to train multiple probes at once, and log
their performance to Weights & Biases

# Bonus

Finally, we'll take a look at some future directions which could come from this
OthelloGPT analysis. We strongly recommend you
follow some of these threads of research yourself,
and see where they might lead!
"""

# %%
# Setup code

import copy
import os
import sys
from dataclasses import dataclass
from functools import partial
from pathlib import Path
from typing import Callable

import einops
import numpy as np
import pandas as pd
import plotly.express as px
import torch as t
import wandb
from eindex import eindex
from IPython.display import HTML, display
from jaxtyping import Bool, Float, Int
from torch import Tensor
from tqdm.notebook import tqdm
from transformer_lens import ActivationCache, HookedTransformer, HookedTransformerConfig
from transformer_lens.hook_points import HookPoint
from transformer_lens.utils import download_file_from_hf, get_act_name, to_numpy

device = t.device("mps" if t.backends.mps.is_available() else "cuda" if t.cuda.is_available() else "cpu")

# Make sure exercises are in the path
chapter = "chapter1_transformer_interp"
section = "part53_othellogpt"
root_dir = next(p for p in Path.cwd().parents if (p / chapter).exists())
exercises_dir = root_dir / chapter / "exercises"
section_dir = exercises_dir / section
if str(exercises_dir) not in sys.path:
    sys.path.append(str(exercises_dir))

import part53_othellogpt.tests as tests
import part53_othellogpt.utils as utils
from neel_plotly import scatter

t.set_grad_enabled(False)

MAIN = __name__ == "__main__"

# %% [markdown]

"""
[1] Model Setup & Linear Probes

Learning Objectives
- Understand the basic structure of the Othello-GPT model
- Become familiar with the basic tools we'll use
for board visualization during these exercises
- See how our linear probe works, and how we can
change basis between "black/white piece" and "mine/their piece"
- Intervene with the linear probe to influence model predictions

For those unfaimilar, Othello is a board game analogous
to chess or go, with two players, black and white, see
the rules outlined in the figure below. I found
playing the AI on Othello helpful for building
intuition. A single move can change the colour of pieces
far away (so long as there's a continuous vertical,
horizontal or diagonal line), which means that
calculating board state is actually pretty hard!
(to my eyes much harder than in chess)

[image](https://res.cloudinary.com/lesswrong-2-0/image/upload/f_auto,q_auto/v1/mirroredImages/nmxzr2zsjNtjaHh7x/eoi5u5fodorjswnmbqk7)

# Background - Othello, and OthelloGPT
But despite the model just needing to predict the
next move, it spontaneously learned to compute the
full board state at each move - a fantastic result.
A pretty hot question right now is whether LLMs
are just bundles of statistical correlations or have
some real understanding and computation! This gives
suggestive evidence that simple objectives to predict
the next token can create rich emergent structure
(at least in the toy setting of Othello). Rather than
just learning surface level statistics about the
distribution of moves, it learned to model the
underlying process that generated that data.
In my opinion, it's already pretty obvious that transformers
can do something more than statistical correlations
and pattern matching, see eg induction heads, but
it's great to have clearer evidence of fully-fledged world
models!

For context on my investigation, it's worth
analysing exactly the two pieces of evidence they
had for the emergent world representation, the probes
and the causal itnerventions, and their strengths and
weaknesses.

# Probes

The probes give suggestive, but far from
conclusive evidence. When training a probe to extract
some feature from a model, it's easy to trick yourself.
It's crucial to track whether the probe is just
reading out the feature, or actually compute
the feature itself, and reading out
much simpler features from the model. In the
extreme case, you could attach a much more
powerful model as your "probe", and have it just extract
the input moves, and then compute the
board state from scratch! They found that linear
probes did not work to recover board state
(with an error rate of 20.4%): (ie, projecting the
residual stream onto some 3 learned directions for each
square, corresponding to empty, black and white logits).
While the simpelst non-linear probes (a two layer MLP
with a single hidden ReLU layer) worked extremely
well (an error rate of 1.7%). Further (as described
in their table 2, screenshot below), these non-linear
probes did not work on a randomly initialised network,
and worked better on some layers than others,
suggesting they were learning something real
from the model

# Causal interventions

Probes on their own can mislead, and don't necessarily
tell us that the model uses this representation -
the probe could be extracting some vestigial
features or a side effect of some more useful
computation, and give a misleading picture of how
the model computes the solution. But their causal
interventions make this much mroe compelling evidence.
They intervene by a fairly convoluted process
(detailed in the figure below, though you don't 
need to understand the details), which boils down
to choosign a new board state, and applyign gradient descent
to the model's residual stream such that our probe
thinks the meodel's residual stream represents the new board
state. I have an immediate skepticism of any complex
technique like this: when applying a powerful
method like gradient descent it's so easy to
wildly diverge from what the models original
functioning is like! SBut the fact that the model
could do the non-trivial computation of converting
an edited board state into a legal move post-edit
is a very impressive result! I consider it very strong
evidence both that the probe has discovered something
real, and that the representation found by the probe
is causally linked to the model's actual computation!

# Naive Implications for Mechanistic Interpretability

I was very interested in this paper, because it simultaneously
had the fascinating finding of an emergent world model
(and I'm als ogenerally into any good interp apper),
yet something felt off. The techniques used here seemed
"too" powerful. The results were strong enough
that something here seemed clearly real, but my intuition
is that if you've really understood a model's itnernals, you should
just be able to understand and manipulate it with
far simpler techniques, like linear probes and interventions,
and it's easy to be misled by more powerful techniques.

In particular, my best guess about model itnernals is
that the networks form decomposable, linear represnetations:
that the model computes a bunch of useful features, and represents these
as directions in activation space. See Toy Models of Superisition
for some excellent exposition on this. This is
decomposable because each feature can vary independently (from the
perspective of the model - on the data distribution they're likely dependent),
and linear because we can extract a feature by projecting
onto that feature's direction (if the features are orthogonal
if we have something like superposition it's messier).
This is a natural way for models to work - they're
fundamentally a series of matrix multiplications with
some non-linearities stuck in convenient places,
and a decomposable, linear representation allows
it to extract any combination of features with a linear map!

Under this framework, if a feature can be found by a linear
probe then the model has already computed it, and if
that feature is used in a circuit downstream,
we sohuld be able to causally intervene with a linear
intervention, just changing the coordinate along
that feature's direction. So the fascinating
finding that linear probes do not work, 
but non-linear probes do, suggests that either
the model has a fundamentally non-linear representation
of features (which it is capable of using directly
for downstream computation!), or there's a linear
representation of simpler and more natural features,
from which the probe computes board state. My prior
was on a linear representation of simpler features,
but the causal intervention findings felt like moderate
evidence for the non-linear representation. And
the non-linear representation hypothesis would be
a big deal if true! If you want to reverse-engineer
a model, you need to have a crisp picture of how
its computation maps onto activations and weights,
and this would break a lot of my beliefs about how
this correspondance works! Furher, linear
representations are just really convenient to
reverse-engineer, and this would make me
notably more perssimistic about mechanistic interpretability
working.

# Model Setup & Visaulization

The best way to become less confused about a mysterious
model behavior is to mechanistically analyse it.
To zoom in on whatever features and circuits
we can find, build our understanding from the
bottom up, and use this to form grounded beliefs
about what's actually going on.

To get started, let's load in the model that we'll
be using for this chapter. A few important technical
details:
- Othello games have 60 moves (the board has size
8x8, and the middle 4 squares are all occupied,
so by 60 moves all squares are occupied by some
color). The model's context length is 59,
because it's learned to take in moves[0:59] and
predict moves[1:60]
- The dataset the model was trained on
just consists of randomly sampeld legal moves.
A move in Othello is legal if and only if
it captures the opponents' pieces in a horizontal,
vertical, or diagonal line - in which case it flips
all those pieces to its own color. This means
predicting next legal moves is a nontrivial task
(one might guess it requires the model to track
captures and board states over time)
  - Because the model was trained on cross entropy
    loss against the actual next moves, the model's
    distribution converges to uniform over all
    next legal moves - can you see why?

<details>
<summary>Proof - why the model learns a uniform
distribution over next legal moves</summary>
The cross entropy loss is defined as $H(p,q)=-\sum_x p(x) \log q(x)$,
which by Gibb's inequality is minimized when p(x) = q(x).
So we minimize loss when the model's distribution q
matches the underlying data distribution p, 
which is uniform over next legal moves.

Note we can also prove this using Jensen's inequality,
since $\log q(x)$ is a strictly concave function.
Alternatively, we can express the cross entropy
loss as the sum of the underlying data distribution's
entropy and the KL divergence between the model's
distribution and the underlying distribution:

$H(p,q) = -\sum_x p(x) \log q(x) = \sum_x p(x) \log \frac{p(x)}{q(x)} - \sum_x p(x) \log p(x) = D_{KL}(p||q) + H(p)$

so this statement becomes equivalent to the
statement that D_{KL}(p||q) is always non-negative
and is only zero when p(x) = q(x) (which can be
provide in similar ways)
</details>

- The vocabulary size is 61, because we allow
  any of the 8x8 - 4 = 60 unoccupied squares to be
  played, plus the pass move. The vocab is ordered
  `pass, A0, A1, ..., H7`, Note that we'll be filtering
  out games where a `pass` move was played, so we don't
  need to worry about this.
- We'll refer to squares in 3 different ways:
  1. label - this is the string representation,
     i.e. `"pass"`, `"A0"`, `"A1"`, ..., `"H7"`.
  2. token id, or id - this is the token ID in the
     model's vocab, i.e. for `1` for A0, ..., `60` for H7.
     We skip `0` which is the token id for `pass`,
     and we skip the 4 middle squares since they're
     always occupied and so there are no moves
     in or predictions for these squares.
  3. square index, or square - this is the zero-ndexed
     value of the square in the size-64 board,
     i.e. `0` for A0, `1` for A1, ..., `63` for H7.
- Black plays first in Othello, and so (in games
  with no passes) White plays last. Since we
  don't predict the very first move, this means the
  model's predictions are for (white 1, black 2,
  white 2, ..., white 29, black 30, white 30)
"""

# %%
"""
Run the code below to load in the model
"""

cfg = HookedTransformerConfig(
  n_layers=8,
  d_model=512,
  d_head=64,
  n_heads=8,
  d_mlp=2048,
  d_vocab=61,
  n_ctx=59,
  act_fn="gelu",
  normalization_type="LNPre",
  device=device,
)
model = HookedTransformer(cfg)

model_path = f"{WORKSPACE}/NeelNanda/Othello-GPT-Transformer-Lens/synthetic_model.pth"
# model_path = f"{WORKSPACE}/NeelNanda/Othello-GPT-Transformer-Lens/championship_model.pth"

state_dict = t.load(model_path, map_location=device)

# use this if you can access huggingface.co directly
# state_dict = download_file_from_hf("NeelNanda/Othello-GPT-Transformer-Lens", "synthetic_model.pth")
# state_dict = download_file_from_hf("NeelNanda/Othello-GPT-Transformer-Lens", "championship_model.pth")

model.load_state_dict(state_dict)

# %%

"""
Next, run the code below to check that the model
is working correctly. Our `sample_input` is a
sequence of 10 moves (the first 10 moves of the
game, starting with black's 1st move and ending
in white's 5th move).
"""

# An example input: 10 moves in a game
sample_input = t.tensor([[20, 19, 18, 10, 2, 1, 27, 3, 41, 42]]).to(device)

logits = model(sample_input)
logprobs = logits.log_softmax(-1)

assert logprobs.shape == (1, 10, 61)  # shape is [batch, seq_len, d_vocab]
assert logprobs[0, 0].topk(3).indices.tolist() == [21, 33, 19]  # these are the 3 legal moves, as we'll soon show

# %%

"""
Note that we can convert each of our logprob vectors
(which have shape `(61,)` into a board state
tensor of shape `(8,8)` (we put very
negative values in the 4 middle squares) via
some clevery indexing. Then, we can plot the
results using a helper function `utils.plot_board.values`
we've written for you. Since you'll be using this function a lot
in subsequent exercises, we'll go through the important arguments here:
- `state`: a tensor of shape (*N, 8, 8), where `*N` is any number
  of batch dimensions. For each `N` tensors, we'll
  visualize a single 8x8 grid. If the shape is `(8,8)`
  then we'll plot a single board.
- `board_titles`: if plotting multiple boards (i.e., 
  `N >`) then we can use this argument to label each of them.
- `boards_per_row`: if plotting multiple boards,
  we can set this many boards per row
- `text`: an optional list of strings with
  the same shape as `state`, which we can use to
  annotate the boards. Also fine for it to be
  broadcastable to the shape of `state` (e.g.
  it can be `(8, 8)` even if `state` is 3D)
- `kwargs`: other arguments get passed into
  `px.imshow` (e.g. `title`, `width`, and `height`)

Understanding exactly how this function works isn't
important, since you can always copy and paste
code from one of the following examples if you
forget how to use it!
"""

# %%

MIDDLE_SQUARES = [27, 28, 35, 36]
ALL_SQUARES = [i for i in range(64) if i not in MIDDLE_SQUARES]

logprobs_board = t.full(size=(8, 8), fill_value=-13.0, device=device)
logprobs_board.flatten()[ALL_SQUARES] = logprobs[0, 0, 1:]  # the [1:] is to filter out logits for the "pass" move

utils.plot_board_values(logprobs_board, title="Example Log Probs", width=500)

# %%

"""
<details>
<summary>Aside - how does this tensor indexing magic work?</summary>

`temp_board_state` is an array of shape `(8, 8)`.
When we use `.flatten()`, this returns a view
(i.e. same underlying data) with shape `(64,)`.
When we index it by `ALL_SQUARES` (a list of
60 indices, which is all the indices excluding the
"middle squares"), this also returns a view
(still the same data). We can then set those
60 elements to be the model's log probs.
This will change the values in the original tensor,
without changing that tensor's shape.
</details>
"""

# %%

"""
We can use the `text` argument to annotate all
the legal squares with their token IDs, which
might be easier in some cases. Here's an example
(you might want to reuse this code in some
later exercises):
"""
SQUARE_TO_TOKEN_ID = {sq: i + 1 for i, sq in enumerate(ALL_SQUARES)}
TOKEN_IDS_2D = np.array([str(SQUARE_TO_TOKEN_ID[i]) if i in ALL_SQUARES else "" for i in range(64)]).reshape(8, 8)
BOARD_LABELS_2D = np.array(["ABCDEFGH"[i // 8] + f"{i % 8}" for i in range(64)]).reshape(8, 8)

print(TOKEN_IDS_2D)
print(BOARD_LABELS_2D)

utils.plot_board_values(
  t.stack([logprobs_board, logprobs_board]),  # shape (2, 8, 8)
  title="Example Log Probs (with annotated token IDs)",
  width=800,
  text=np.stack([TOKEN_IDS_2D, BOARD_LABELS_2D]),  # shape (2, 8, 8)
  board_titles=["Labelled by token ID", "Labelled by board label"],
)

# %%

"""
We can also use this function to plot multiple
board states at once, exactly the same way.
Again pay attention to the indexing, because
understanding how this works will be useful
going forwards
"""

logprobs_multi_board = t.full(size=(10, 8, 8), fill_value=-13.0, device=device)
logprobs_multi_board.flatten(1, -1)[:, ALL_SQUARES] = logprobs[0, :, 1:]  # we now do all 10 moves at once

utils.plot_board_values(
    logprobs_multi_board,
    title="Example Log Probs",
    width=1000,
    boards_per_row=5,
    text=TOKEN_IDS_2D,
    board_titles=[f"Logprobs after move {i}" for i in range(1, 11)],
)

# %%

"""
Let's use the same function to plot the first 10
board states, and check that the predictions shown
above make sense given the board state at
that time. We'll use a helper method `OthelloBoardState`
to track the board state after each move
"""

board_states = t.zeros((10, 8, 8), dtype=t.int32)
legal_moves = t.zeros((10, 8, 8), dtype=t.int32)

board = utils.OthelloBoardState()
for i, token_id in enumerate(sample_input.squeeze()):
  # board.umpire takes a square index (i.e. from 0 to 63) and makes a move on the board
  board.umpire(utils.id_to_square(token_id))

  # board.state gives us the 8x8 numpy array of 0 (blank), -1 (black), 1 (white)
  board_states[i] = t.from_numpy(board.state)

  # board.get_valid_moves() gives us a list of the indices of squares that are legal to play next
  legal_moves[i].flatten()[board.get_valid_moves()] = 1

# Turn `legal_moves` into strings, with "o" where the move is legal and empty string where illegal
legal_moves_annotation = np.where(to_numpy(legal_moves), "o", "").tolist()

utils.plot_board_values(
  board_states,
  title="Board states",
  width=1000,
  boards_per_row=5,
  board_titles=[f"State after move {i}" for i in range(1, 11)],
  text=legal_moves_annotation,
)

"""
In this plot you should see that each board state
evolves from the previous one via a single move
that captures a set of pieces from the opposing
color (e.g. in the first move black plays `C3`
capturing white at `D3`, and in the second move
white plays `C2` and captures black diagonally
at `D3`). You sohuld also see that the
annotated legal moves match the moves predicted
by the model.
"""

# %%

"""
# Data

Let's no load some data for OthelloGPT. We'll load
data in `id` format (i.e. 1 to 60 inclusive, since
our vocab is range (0,61) and we're filtering
out games with pass moves) and `int` format
(i.e. 0 to 63 inclusive, since the games contain
moves from `A0` to `H7`)
"""

board_seqs_id = t.from_numpy(
  np.load(section_dir / "board_seqs_id_small.npy")
).long()
board_seqs_square = t.from_numpy(
  np.load(section_dir / "board_seqs_square_small.npy")
).long()

print(
  f"board_seqs_id: shape {tuple(board_seqs_id.shape)}, range: {board_seqs_id.min()} to {board_seqs_id.max()}"
)
print(
  f"board_seqs_square: shape {tuple(board_seqs_square.shape)}, range: {board_seqs_square.min()} to {board_seqs_square.max()}"
)

"""
Note - you can access a larger dataset at
the GitHub readme, in the "Training Othello-GPT"
section. There are links to download datasets
from Google Drive (both synthetic and championship games).
You can store them in your `data` folder, after you've cloned the repo using the code above
"""

# %%

"""
# Making some utilities

At this point, we'll stop and get some aggregate
data that will be useful later - a tensor of valid moves,
of board states, and a cache of all model activations across
50 games (in practice, you want as much as will comfortably fit into GPU memory).
It's really convenient to have the ability to quickly run an experiment
across a bunch of games! And one of the great things 
about small models on algorithmic tasks is that
you just can do stuff like this

Let's call these the focus games
"""

def get_board_states_and_legal_moves(
  games_square: Int[Tensor, "n_games n_moves"],
) -> tuple[
  Int[Tensor, "n_games n_moves rows cols"],
  Int[Tensor, "n_games n_moves rows cols"],
  list,
]:
  """
  Returns the following:
      states:                 (n_games, n_moves, 8, 8): tensor of board states after each move
      legal_moves:            (n_games, n_moves, 8, 8): tensor of 1s for legal moves, 0s for illegal moves
      legal_moves_annotation: (n_games, n_moves, 8, 8): list containing strings of "o" for legal moves (for plotting)
  """
  # Create tensors to store the board state & legal moves
  n_games, n_moves = games_square.shape
  states = t.zeros((n_games, 60, 8, 8), dtype=t.int32)
  legal_moves = t.zeros((n_games, 60, 8, 8), dtype=t.int32)

  # Loop over each game, populating state & legal moves tensors after each move
  for n in range(n_games):
    board = utils.OthelloBoardState()
    for i in range(n_moves):
      board.umpire(games_square[n, i].item())
      states[n, i] = t.from_numpy(board.state)
      legal_moves[n, i].flatten()[board.get_valid_moves()] = 1

  # Convert legal moves to annotation
  legal_moves_annotation = np.where(to_numpy(legal_moves), "o", "").tolist()

  return states, legal_moves, legal_moves_annotation


num_games = 50

focus_games_id = board_seqs_id[:num_games]  # shape [50, 60]
focus_games_square = board_seqs_square[:num_games]  # shape [50, 60]
focus_states, focus_legal_moves, focus_legal_moves_annotation = get_board_states_and_legal_moves(focus_games_square)

print("focus states:", focus_states.shape)
print("focus_legal_moves", tuple(focus_legal_moves.shape))

# Plot the first 10 moves of the first game
utils.plot_board_values(
  focus_states[0, :10],
  title="Board states",
  width=1000,
  boards_per_row=5,
  board_titles=[f"Move {i}, {'white' if i % 2 == 1 else 'black'} to play" for i in range(1, 11)],
  text=np.where(to_numpy(focus_legal_moves[0, :10]), "o", "").tolist(),
)

# %%

"""
Let's also cache all the model's activations
and logits for these focus games
"""

focus_logits, focus_cache = model.run_with_cache(focus_games_id[:, :-1].to(device))

print(focus_logits.shape)  # shape [num_games=50, n_ctx=59, d_vocab=61]

# %% [markdown]

"""
# Recap of the useful objects we've defined

We have the following:

Models
- `model` is an 8-layer autoregressive transformer,
trained to predict elgal Othello moves. Its vocab is
`range(0,61)` where 0 = "pass" and the other
numbers represent the 60 possible moves, excluding the 4 middle squares

All data
- `board_seqs_id`, shape `(100k, 60)` contains the moves from all 100k games (as token ids)
- `board_seqs_square`, shape `(100k, 60)` contains the moves from all 100k games (as ints)

Focus games data
- `focus_games_id`, shape `(50, 60)` 
  contains the moves from 50 games (as token ids)
- `focus_games_square`, shape `(50, 60)` 
  contains the moves from 50 games (as ints)
- `focus_states`, shape `(50, 60, 8, 8)` 
  contains the board states after each move 
  (0 = empty, 1 = black, -1 = white)
- `focus_legal_moves`, shape `(50, 60, 8, 8)` 
  contains a 1 for each legal move, and 0 
  for each illegal move
- `focus_logits`, shape `(50, 59, 61)` 
  contains model's output logits on focus games 
  `59=model.cfg.n_ctx` because we don't include 
  the final move in our forward pass, and
  `61=model.cfg.d_vocab` contains the "pass"
  move and all 60 playable squares
"""

# %% [markdown]

"""
# What is a probe

From the MI Dynalist notes:
> Probing is a technique for identifying directions
> in network activation space that correspond 
> to a concept/feature
>
> In spirit, you give the network a bunch of inputs
> with that feature, and a bunch without it. 
> You train a linear map on a specific activation (
> eg the output of layer 5) which distinguishes these
> two sets, giving a 1D linear map (a probe),
> corresponding to a direction in activation space,
> which likely corresponds to that feature

Probes can be a very valuable tool to help us
better understand the concepts represented in our model.
However, there are two big caveats to keep in mind:
1. Probes give us a direction, but they don't give
   us a causal story about how that direction
   got into the model in the first place, or how
   the model is using that direction
2. Probes (especially nonlinear probes) can be
   hiding a lot of computation under their surface.

In the original paper analysing Othello, the
authors used nonlinear probing to find important
directions. This went against a fundamental
intuition - that models fundamentally store things
in linear ways, and so we should be able to access
them with linear probes. In these exercises, we'll
be using linear probes.
"""

# %%

"""
# Using the probe

The training of this probe was kind of a mess,
and I'd do a bunch of things differently if doing it again

There were 3 different probe modes:
- `full_linear_probe[0].shape` = (d_model, 8, 8, 3)
  was trained on black to play, i.e. odd moes.
  The classes are `[empty, white, black]`.
- `full_linear_probe[1].shape` = (d_model, 8, 8, 3)
  was trained on white to play, i.e. even moves.
  The classes are `[empty, white, black]`.
- `full_linear_probe[2].shape = (d_model, 8, 8, 3)`
  was trained on all moves

For example, we could take `full_linear_probe[0]`
and take the inner product with the residual stream
to get a tensor of shape (8, 8, 3) representing
`8x8=64` separate predictions for what each of the
64 board squares contains (i.e. you'd softmax
this tensor over the last dimension to get probabilities)

Personal notes
- So, for each of the 64 squares, the probe has
  three vectors of size `d_model`. Taking
  the dot product of the model's residual stream with
  `full_linear_probe[0,:, r, c, :]` gives three
  logits, which can be softmaxed to get the probability
  that square `(r,c)` is empty, white or black
- The first dimension of `full_linear_probe` (size
  3) corresponds to different training conditions,
  or "modes", as explained in `answers.py`:
  - `full_linear_probe[0]` (`black_to_play`):
    Trained on board states where it is black's turn
    to play (odd-numbered moves)
  - `full_linear_probe[1]` (`white_to_play`):
    Trained on board states where it is white's turn
    to play (even-numbered moves).
  - `full_linear_probe[2]`: Trained on all moves.

`black_vs_white_dir_odd_moves` and 
`black_vs_white_dir_even_moves`

These variables are calculated to find a single direction
in the residual stream that best distinguishes
between a black piece and a white piece
on any given square
- `black_vs_white_dir_odd_moves = full_linear_probe[black_to_play, :, :, :, black] - full_linear_probe[black_to_play, :, :, :, white]`
  This line computes the "black vs. white" direction for odd moves (when black is to play).
  - `full_linear_probe[black_to_play, ..., black]` is the probe direction for "black"
  - `full_linear_probe[black_to_play, ..., white]` is the probe direction for "white"
  - Subtracting the two gives a direction in the `d_model`-dimensional space.
    Projecting a residual stream activation onto this direction
    will be high if the model represents a black piece and low if it represents a white piece.
- `black_vs_white_dir_even_moves = full_linear_probe[white_to_play, :, :, :, black] - full_linear_probe[white_to_play, :, :, :, white]`
  This does the same for even moves (when white is to play).

What do they compute?
These variables compute the vector directions that represent
the concept of "black piece vs. white piece" for every square
on the board, under different game conditions (odd vs. even moves).

The key insight from the exercise, as stated in `answers.py`, is
that the model doesn't think in terms of "black vs. white" but rather
"my piece vs their piece".
- On odd moves, "mine" is black and "theirs" is white
- On even moves, "mine" is white and "theirs" is black

Therefore, the "black vs. white" direction should be
the opposite of the "white vs. black" direction. This means
`black_vs_white_dir_odd_moves` should be approximately
the negative of `black_vs_white_dir_even_moves`. The
exercise demonstrates this by showing their cosine similarity
is close to -1. This supports the hypothesis that the model
has learned a more abstract, player-centric representation
of the board state
"""

full_linear_probe = t.load(
  section_dir / "main_linear_probe.pth", 
  map_location=str(device), 
  weights_only=True,
)

print(full_linear_probe.shape)

black_to_play, white_to_play, _ = (0, 1, 2)  # = indices along `full_linear_probe.shape[0]`, i.e. the modes
empty, white, black = (0, 1, 2)  # = indices along `full_linear_probe.shape[-1]`, i.e. the possible classifications

# %%

"""
# Exercise - calculate probe cosine similarities

We won't be using `full_linear_probe[2]` much,
since it doesn't work very well.
We'll be focusing on the first two modes.

The key result that was found in this
investigation is that the prob learns
directions in terms of "theirs vs mine"
rather than "black vs white". In this case,
you'd expect the probes for odd and even
moves to be approximately opposite 
to each other (since "thiers vs mine"
has the opposite meaning in odd vs even
moves). Here's a plot visualizing
that we do in fact get this - it shows
cosine similarity of the "black minus white"
directions across each 64 squares in
each of the probe modes. The off diagonal
stripe with values close to negative 1
indicates that the "black minus white"
direction for any given square is
approximately antipodal when taken
at odd vs even modes (marked
with `0` and `E` in the reference plot)

Try to replicate this plot, using just
the `full_linear_probe` that's been
defined for you above. Remember,
it has shape `(modes=3, d_model=512,
rows=8, cols=8, options=3)`: the
first 2 modes are black to play 
/ white to play, and the three options
are empty / white /black. We've given
you the code to create the plot from
the `cosine_similarities` tensor
(which should have the shape `(64*2, 64*2)`),
all you need to do is to create the tensor
"""

# Get the "black vs white" probe directions for odd & even moves respectively
black_vs_white_dir_odd_moves = (
  full_linear_probe[black_to_play, :, :, :, black] - full_linear_probe[black_to_play, :, :, :, white]
)
black_vs_white_dir_even_moves = (
  full_linear_probe[white_to_play, :, :, :, black] - full_linear_probe[white_to_play, :, :, :, white]
)

"""
Personal note
"This line compute the 'black vs. white' direction
for odd moves (when black is to play)" means:
- For each square on the board, the probe has
  a vector for "black" and a vector for "white"
  in the model's activation space (of size `d_model`).
- `full_linear_probe[black_to_play, :, :, :, black]`
  gives you the probe direction for "black" pieces
  on each square, when it is black's turn to play
  (i.e., odd-numbered moves)white
- `full_linear_probe[black_to_play, :, :, :, black]`
  gives you the probe direction for "white" piece on
  each square, when it is black's turn to play
- Subtracting these two vectors for each square
  gives a new vector (the "black vs. white" direction)
  that points in the direction that best distinguishes
  a black piece from a white piece on that square,
  specifically for the context when it is black's turn
"""

# Flatten over (rows, cols) then concatenate them over this dimension
all_dirs = t.stack([black_vs_white_dir_odd_moves, black_vs_white_dir_even_moves])
all_dirs = einops.rearrange(all_dirs, "parity d_model rows cols -> d_model (parity rows cols)")

"""
Personal note
1. Why do we rearrange `all_dirs` from `parity d_model rows cols`
   to `d_model (parity rows cols)`?
   - After stacking, `all_dirs` has shape `(2, d_model, 8, 8)` (2 parities: odd/even)
   - Rearranging to `(d_model, 128)` (where 128 = 2 x 8 x 8) means:
     - Each column is a probe direction for a specific (parity, row, col)
     - Each row is a particular dimension across all probe directions
   - This format is needed so we can compare all probe directions as vectors in `d_model`-space
"""

# Compute cosine similarities
all_dirs_normed = all_dirs / all_dirs.norm(dim=0, keepdim=True)
cosine_similarities = einops.einsum(
  all_dirs_normed, all_dirs_normed, "d_model mode_row_col_1, d_model mode_row_col_2 -> mode_row_col_1 mode_row_col_2"
)

# Personal answer
all_dirs = t.stack([black_vs_white_dir_odd_moves, black_vs_white_dir_even_moves])
all_dirs_normed = all_dirs / all_dirs.norm(dim=1, keepdim=True)
all_dirs_normed = einops.rearrange(all_dirs_normed, "parity d_model rows cols -> d_model (parity rows cols)")
cosine_similarities = all_dirs_normed.T @ all_dirs_normed

"""
Personal note
2. Why do we compute cosine similarity between these vectors?
   - Each column of `all_dirs_normed` is a probe
     direction for a specific square and parity i.e. (parity, row, col)
   - By computing cosine similarity between all pairs,
     we see how similar or different
     the probe directions are for different squares
     and parities
   - This helps us discover patterns, like whether
     the model uses similar directions for
     the same square across parities, or if they
     are opposite (as in the "mine vs theirs" hypothesis)

You only need to care about one of the off-diagonal
stripes, both stripes are essentailly mirror
images of each other due to the symmetry of
the cosine similarity matrix

3. Why are there two off-diagonal stripes?
   - The cosine similarity matrix is square
     and symmetric: `cosine_similarities[i, j] == cosine_similarities[j, i]`
   - Each off-diagonal stripe corresponds to
     comparing the probe direction for a given
     square in odd moves (black to play) with
     the same square in even moves (white to play),
     and vice versa.
   - The two stripes are redundant: one is the
     transpose of the other

4. What does it mean when the off-diagonal stripe has values close to -1?
   - For a given square, the probe direction for "black vs white"
     on odd moves is almost the opposite of the direction on even moves.
   - Cosine similarity close to -1 means the two vectors
     point in exactly opposite directions
   - Interpretation:
     The model represents "mine vs theirs" rather
     than "black vs white."
     - On odd moves, "mine" is black, "theirs" is white
     - On even moves, "mine" is white, "theirs" is
       black. So, the direction that means "mine"
       flips sign depending on whose turn it is
```python
# A shape [parity=2, d_model=2, rows=2, cols=2]
A = t.arange(0, 2 * 2 * 2 * 2, dtype=t.float32).reshape(2,2,2,2)

B = einops.rearrange(A, "parity d_model rows cols -> d_model (parity rows cols)")

print(f"A:\n{A}")
print(f"B.T:\n{B.T}")
print(f"B:\n{B}")
```
"""

fig = px.imshow(
  to_numpy(cosine_similarities),
  title="Cosine Sim of B-W Linear Probe Directions by Cell",
  x=[f"{L} (O)" for L in BOARD_LABELS_2D.flatten()] + [f"{L} (E)" for L in BOARD_LABELS_2D.flatten()],
  y=[f"{L} (O)" for L in BOARD_LABELS_2D.flatten()] + [f"{L} (E)" for L in BOARD_LABELS_2D.flatten()],
  width=900,
  height=800,
  color_continuous_scale="RdBu",
  color_continuous_midpoint=0.0,
)
fig.show()

"""
Personal note
1. The `einsum` Operation
The operation is: "m n, m p -> n p"

This is a more explicit way of writing
a matrix multiplication: `Dᵀ @ D` (the transpose
of `D` multiplied by `D`).

Let's break down the string:
- `m n`: This names the axes of the first input (D).
  `m` is the dimension of size 2, and `n` is
  the dimension of size 2.
- `m p`: This names the axes of the second input (also `D).
  `m` is the same shared dimension, and `p` is the
  dimension of size 2.
- `-> n p`: This specifies the output. Notice `m`
  is gone. This means we sum over that dimension
- 

```python
D = t.arange(2, 2 + 2 * 2, dtype=t.float32).reshape(2,2)

print(D @ D)
print(einops.einsum(D, D, "m n, n p -> m p"))

print(D.T @ D)
print(einops.einsum(D, D, "m n, m p -> n p))

print((D.T @ D).T)
print(einops.einsum(D, D, "m n, m p -> p n))
```
"""

# %%

"""
# Changing probe basis

Now we've established that the probe directions
are very similar, let's just average them
to create our probe in a new basis: the "theirs vs mine"
basis, not the "black vs white" basis. For example,
our new probe's "theirs" direction will be the average
of the white direction when black is to play,
and the black direction when white is to play
"""

linear_probe = t.stack(
  [
    full_linear_probe[[black_to_play, white_to_play], ..., [empty, empty]].mean(0),  # "empty" direction
    full_linear_probe[[black_to_play, white_to_play], ..., [white, black]].mean(0),  # "theirs" direction
    full_linear_probe[[black_to_play, white_to_play], ..., [black, white]].mean(0),  # "mine" direction
  ],
  dim=-1,
)

"""
Personal note
2. Why does the shape become (2, 512, 8, 8) and not (2, 512, 8, 8, 2)?
- When you use advanced indexing like this,
  PyTorch matches the first and last indices elementwise:
  - For the first element: `full_linear_probe[0, ..., 1]` (black_to_play, white)
  - For the second element: `full_linear_probe[1, ..., 2]` (white_to_play, black)
- The result is a tensor where each element along the first axis
  is a `(d_model, 8, 8)` tensor, so the output shape is
  `(2, d_model, 8, 8)`

```python
A = t.arange(0, 3 * 2 * 2 * 2 * 3, dtype=t.float32).reshape(3, 2, 2, 2, 3)
print(A[0, ..., 1])
print(A[[0,1], ..., [1,2]])
```
"""

# %%

"""
Let's test out our new probe, by applying it to
move 29 in game 0 from our focus games. This is
an odd move, so black is to play.
"""

def plot_probe_outputs(
  cache: ActivationCache, 
  linear_probe: Tensor, 
  layer: int, 
  game_index: int, 
  move: int, 
  title: str = "Probe outputs",
):
  residual_stream = cache["resid_post", layer][game_index, move]
  probe_out = einops.einsum(residual_stream, linear_probe, "d_model, d_model row col options -> options row col")

  utils.plot_board_values(
    probe_out.softmax(dim=0),
    title=title,
    width=900,
    height=400,
    board_titles=["P(Empty)", "P(Their's)", "P(Mine)"],
    # text=BOARD_LABELS_2D,
  )

layer = 6
game_index = 0
move = 29

utils.plot_board_values(
  focus_states[game_index, move],
  title="Focus game states",
  width=400,
  height=400,
  text=focus_legal_moves_annotation[game_index][move],
)

plot_probe_outputs(
  focus_cache,
  linear_probe,
  layer,
  game_index,
  move,
  title=f"Probe outputs after move {move} (black to play)",
)

# %%

"""
Moving back to layer 3, it seems the model
already has a pretty good board state
representation by this point, but it's missing
a few things (most notably it thinks C5 and
especially C6 are white when they're actually black).
My guess is that the board state calcualtion circuits
haven't quite finished and are doing some
iterative reasoning - if those cells have been taken
several times, maybe it needs a layer to
track the next earliest time it was taken? 
I don't know, and figuring this out would be great 
starter project if you want to explore!
"""

layer = 3
game_index = 0
move = 29

plot_probe_outputs(
  focus_cache,
  linear_probe,
  layer,
  game_index,
  move,
  title=f"Probe outputs (layer {layer}) after move {move} (black to play)",
)

# %%

"""
Now let's take one step forward - we should
see the representations totally flip. This is
indeed what we find
"""

layer = 4
game_index = 0
move = 30

utils.plot_board_values(
  focus_states[game_index, move],
  text=focus_legal_moves_annotation[game_index][move],
  title="Focus game states",
  width=400,
  height=400,
)
plot_probe_outputs(
  focus_cache, 
  linear_probe, 
  layer, 
  game_index, 
  move, 
  title=f"Probe outputs (layer {layer}) after move {move} (white to play)"
)

"""
Note that the model gets the corner wrong in
this case (incorrectly thinknig that the
corner is white rather than empty) - it's not
a big deal, but interesting!

Can you think of a reason why corners might
be treated differently in this model?

<details>
<summary>Hint</summary>
One possible reason is to do with the rules of
Othello, and how the corners have a special
significance. What happens to a piece once
it's placed in the corner?
</details>

<details>
<summary>One possible reason</summary>
A fact about Othello is that a piece in the
corners can never be flanked and thus
will never change colour once placed - perhaps
the model has decided to cut corners and have
different and less symmetric circuit for these?

Trying to locate this circuit might be a fun
bonus exercise!
</details>
"""

# %%

"""
# Computing accuracy

Hopefully I've convinced you anecdotally that
a lienar probe works. But to be more rigorous,
let's check accuracy across our 50 games.
"""

# Create a tensor of "their vs mine" board states (by flipping even parities of the "focus_states" tensor)
focus_states_theirs_vs_mine = focus_states * (-1 + 2 * (t.arange(focus_states.shape[1]) % 2))[None, :, None, None]

# Convert values (0: empty, 1: theirs, -1: mine) to (0: empty, 1: theirs, 2: mine)
focus_states_theirs_vs_mine[focus_states_theirs_vs_mine == 1] = 2
focus_states_theirs_vs_mine[focus_states_theirs_vs_mine == -1] = 1

# Get probe values at layer 6, and compute the probe predictions
probe_out = einops.einsum(
  focus_cache["resid_post", 6],
  linear_probe,
  "game move d_model, d_model row col options -> game move row col options",
)
probe_predictions = probe_out.argmax(dim=-1)

"""
Personal note:
Why this einsum?
- `focus_cache["resid_post", 6]` is the residual
  stream activation at alyer 6 for each game and
  move, shape `(game, move, d_model)`
- `linear_probe` contains the probe directions
   for each board square and class (empty/theirs/mine),
   shape `(d_model, row, col, options)`

The einsum computes, for each game, move, row, col,
and option:
- The dot product between the residual stream
  vector and the probe direction for that square
  and option

Why sum over the `d_model` dimension?
- The sum over `d_model` is the dot product between
  the model's activation and the probe direction
- This projects the activation onto the probe
  direction, giving a logit (score) for each class
  (empty/theirs/mine) for each square

Why is this considered as probe predictions?
- For each square, you get three logits (one for each class)
- Taking `argmax` over the options dimension gives the predicted class for that square
- This is exactly how a linear probe works: it reads out
  the most likely class by projecting onto learned directions
  and picking the highest score

```python
A = t.arange(0, 3 * 4 * 2 * 2 * 3, dtype=t.float32).reshape(3, 4, 2, 2, 3)
B = A.argmax(dim=-1)
print(A.shape)
print(B.shape)
```
"""

# Get accuracy at odd, even & all moves (average over games & moves)
correct_middle_odd_answers = (probe_predictions.cpu() == focus_states_theirs_vs_mine[:, :-1])[:, 5:-5:2]
accuracies_odd = einops.reduce(correct_middle_odd_answers.float(), "game move row col -> row col", "mean")

correct_middle_even_answers = (probe_predictions.cpu() == focus_states_theirs_vs_mine[:, :-1])[:, 6:-5:2]
accuracies_even = einops.reduce(correct_middle_even_answers.float(), "game move row col -> row col", "mean")

correct_middle_answers = (probe_predictions.cpu() == focus_states_theirs_vs_mine[:, :-1])[:, 5:-5]
accuracies = einops.reduce(correct_middle_answers.float(), "game move row col -> row col", "mean")

# Plot accuracies
utils.plot_board_values(
  1 - t.stack([accuracies_odd, accuracies_even, accuracies], dim=0),
  title="Average Error Rate of Linear Probe",
  width=1000,
  height=400,
  board_titles=["Black to play", "White to play", "All moves"],
  zmax=0.25,
  zmin=-0.25,
)

"""
Note that we can see the probe is worse 
near corners, as we anecdotally observed
"""

# %%

"""
# Intervening with the probe

One of the really exciting consequences of a linear
probe is that it gives us a set of interpretable
directions i nthe residual stream! And with this,
we can not only interpret the model's representations,
but we can also intervene in the model's reasoning.

The first step is to convert our probe to
meaningful directions. Each square's probe has
3 vectors, but the logits go into a softmax,
which is translation invariant, so this only
has two degrees of freedom. A natural-ish way
to convert it into two vectors is taking
`blank - (mine + theirs)/2` giving a
"is this cell empty or not" direction and 
mine - theirs giving a "conditional on being
blank, is this my colour vs their's" direction

<details>
<summary>Help - I'm confused by this</summary>
If you've done the indirect object exercises,
this is similar to looking at the "John" - "Mary"
direction in the logit output - i.e. we take
the difference between two logits, and this gets
us the log-likelihood ratio between these two options,
and this gets us the log-likelihood ratio between
these two options

It's slightly less principled when we're dealing
with more than two different logits, because
the nonlinearities get messy. However, using
`blank - (mine + theirs)/2` is still a pretty
reasonable metric:
- It's symmetrics in `mine` and `theirs`
- It's translation invariant (i.e. you could add 
  constant `c` onto all of `blank`, `mine`, and `theirs` 
  and it wouldn't change)
- If you increase `blank` by some amount `c`
  and keep the other two the same, then this
  metric also increases by `c`

The `mine - theirs` direction is more principled
</details>

Having a single meaningful direction is important,
because it allows us to interpret a feature or
intervene on it. The original three directions
has one degree of freedom,
so each direction is arbitrary on its own

Personal note:
1. "It's slightly less principled when we're
    dealing with more than two different logits,
    because the nonlinearities get messy."
    - When you have only two logits (e.g., "mine"
      vs "theirs"), taking their difference directly
      gives you the log-odds (log-likelihood ratio)
      between the two classes, which is a very principled
      and interpretable metric
      - Why taking their difference directly
        gives you the log-odds (log-likelihood ratio)?
        - Suppose you have two logits, `a` (for "mine")
          and `b` (for "theirs"). The softmax probabilities are:
          P(mine) = exp(a) / exp(a) + exp(b)
          P(theirs) = exp(b) / exp(a) + exp(b)
        - The log-odds (log-likelihood ratio) of "mine" vs "theirs" is:
          log(P(mine) / P(theirs)) = log(e^a / e^b) = a - b
    - With three logits (e.g., "blank", "mine",
      "theirs"), the softmax introduces more complex
      relationships (nonlinearities) between the
      logits, so combining them (like `blank - (mine + theirs)/2`
      is more of a heuristic than a mathematically "pure" log-odds)
    - In other words, the interpretation is less direct,
      but it's still a useful and reasonable way to summarize "empty vs not empty".
2. "It's symmetric in `mine` and `theirs`"
   - The formula `blank - (mine + theirs)/2`
     treats "mine" and "theirs" equally: swapping
     their values doesn't change the result
     - Why is this good?
       It means the metric does not favor "mine"
       or "theirs", it treats both classes equally
       when measuring "is this cell empty or not?".
       This makes the metric unbiased with respect
       to which player owns the piece
   - This symmetry is desirable because we want
     the "empty vs not empty" metric to be unbiased
     with respect to which player owns the piece
3. "If you increase `blank` by some amount `c`
   and keep the other two the same, then this metric
   also increases by "c"`
   - If you add a constant to the "blank" logit,
     the metric becomes `(blank + c) - (mine + theirs)/2
     = (blank - (mine + theirs)/2) + c`
   - So, the metric increases by exactly `c`.
   - This property means the metric responds linearly
     to changes in the "blank" logit, making it
     easy to interpret
4. Why do we want to increase `blank` by some amount `c`
   and keep the other two the same?
   - This is thought experiment to show that
     the metric is sensitive only to the "blank"
     logit, not affected by the absolute values
     of "mine" or "theirs"
   - It demonstrates that the metric is robust
     to global shifts and only reflects the relative
     likelihood of "empty" compared to "occupied"
5. "The original three directions has one degree
    of freedom, so each direction is arbitrary
    on its own"
   - Because of softmax translation invariance,
     only the differences between the three
     logits matter; you can add any constant
     to all three and the probabilities won't change
   - This means the three logits (directions) are
     not all independent, only two are. The third
     is determiend by the other two up to a constant
     shift
   - So, any single direction (logit) by itself is
     arbitrary; only their differences are meaningful

Summary:
- The `blank - (mine + theirs)/2` metric is a
  practical, symmetric, and robust way to distinguish
  "empty" from "not empty" even though it's not
  as mathematically pure as the two-class case
- The metric's properties make it interpretable
  and robust to shifts, and the softmax's translation
  invariance means only difference between logits
  matter, not their absolute values
"""

"""
Personal note:
> Each square's probe has 3 vectors, but the
> logits go into a softmax,
> which is translation invariant,
> so this only has two 3 degrees of freedom

It means:
- For each sqsuare, the probe outputs 3 logits
  (scores), one for each class (empty, mine, theirs)
- These logits are passed through a softmax,
  to get probabilities

Softmax is translation invariant:
If you add the same constant to all logits,
the output probabilities do not change.
Mathematically, for logits `[a,b,c]` and any
constant `k`:
```
softmax([a, b, c]) == softmax([a+k, b+k, c+k])
```

This is because the softmax computes:
```
exp(a) / (exp(a) + exp(b) + exp(c)), etc.
```
and adding `k` to all logits multiplies the numerator
and denominator by `exp(k)`, which cancels out

So:
- Only the differences between the logits matter,
  not their absolute values
- This means, although there are 3 logits, only
  2 are independent (the third is determiend by the
  other two up to a constant shift)
- In other words, the 3D logit vector effectively
  lives in a 2D subspace-2 degrees of freedom

Summary:
Because softmax is translation invariant,
only the relative values of the 3 logits mattter,
so there are only 2 degrees of freedom for each
square's probe output

Degrees of freedom refers to the number of
independent values or parameters that can
vary in a system

1. Why does `blank - (mine + theirs)/2` 
   give an "is this cell empty or not" direction?
   - For each square, the probe outputs three logits:
     `[blank, theirs, mine]`
   - If you take the average of the "theirs" and
     "mine" logits, you get the typical value
     for a non-empty cell.
   - Subtracting this average from the "blank"
     logit gives you a direction that is high
     when the cell is empty and low when it is
     not occupied (regardless of who owns it).
   - So, this direction answers: "is this cell empty
     or not?"

     Example:
     If `[blank, theirs, mine] = [3, 1, 2]` then
     `blank - (mine + theirs)/2 = 3 - (1 + 2)/2 = 3 - 1.5 = 1.5` (positive, so likely empty)
     If `[blank, theirs, mine] = [1, 3, 2]` then
     `blank - (mine + theirs)/2 = 1 - (3 + 2)/2 = 1 - 2.5 = -1.5` (negative, so likely occupied)

2. Why does `mine - theirs` give a "conditional
   on being blank, is this my colour vs their's" direction?
   - Once you know a cell is not empty, you want to know
     whose piece it is
   - The difference `mine - theirs` is positive
     if the cell is yours, negative if it is theirs
   - This direction is only meaningful when
     the cell is not empty (hence "conditional
     on being blank")
   - So, this direction answers: "If this cell is
     occupied, is it mine or theirs?"

Example:
If `[blank, theirs, mine] = [1, 2, 3]`, then
`mine - theirs = 3 - 2 = 1` (yours)
If `[blank, theirs, mine] = [1, 3, 2]`, then
`mine - theirs = 2 - 3 = -1` (theirs)

Summary:
- `blank - (mine + theirs)/2`: High for empty,
  low for occupied (empty vs not).
- `mine - theirs`: High for yours, low for theirs
  (whose piece, if not empty)

This gives you two interpretable, independent 
directions for each square
"""

"""
The reason we don't just use `linear_probe[..., 0]
(the "empty" direction) directly as the "is this cell empty or not"
direction is because of softmax translation invariance
and the need to distinguish "empty" from "not empty"
in a way that's robust to the relevance scale
and offset of the logits

Why not just use `linear_probe[..., 0]`?
- `linear_probe[..., 0]` gives the logit
  for "empty", but the softmax output depends on
  all three logits (`empty`, `theirs`, `mine`), not
  just the "empty" one
- The absolute value of the "empty" logit doesn't
  matter-only its value relative to the other two does

Why use `blank - (mine + theirs)/2`?
- By subtracting the average of the "mine" and "theirs"
  logits from the "empty" logit, you get a direction
  that is high when "empty" is much more likely than
  either "mine" or "theirs"
- This centers the "empty" logit relative to the
  other two, making it a more robust indicator
  of "is this cell empty or not", regardless of
  any constant offset in the logits
- It also matches the fact that, due to softmax
  translation invariance, only the differences
  between logits matter

Analogy
Think of it like this:
- If you want to know if a cell is empty, you don't
  just care about the "empty" score–you care about
  how much higher it is than the average of
  the "occupied" scores.

Summary
- `linear_probe[..., 0]` alone is not enough,
  because softmax only cares about differences.
- `blank - (mine + theirs)/2` gives a direction
  that robustly distinguishes empty from not
  empty, taking into account the relative
  values of all three logits
"""

"""
The concept is similar to mean-centering

When you compute `blank - (mine + theirs)/2`,
you are centering the "empty" logit relative to
the average of the "mine" and "theirs" logits.
This is like subtracting the mean of the "occupied"
logits from the "empty" logit.

Why do this?
- The softmax is only sensitive to the differences
  between logits, not their absolute values
- By centering, you remove any constant offset
  that might be present in all logits (for example,
  if all logits are shifted up or down by the same
  amount, the softmax output doesn't change)
- This makes your "is this cell empty or not"
  direction robust: it only reflects how much
  more likely "empty" is compared to the average
  of the other two options, not affected by 
  any global bias or offset

Analogy to mean-centering:
- In statistics, mean-centering (subtracting the
  mean from each value) removes the overall bias
  and focuses on the variation relative to the mean
  - "Removing the overall bias"
    This means you're shifting the data so that the average
    value becomes zero. For example, if a feature
    like height has a mean of 170 cm, mean-centering
    turns it into a distribution centered around 0
  - "Focus on the variation relative to the mean"
    Once you subtract the mean, you're no longer concerned
    with where the data is cnetered (e.g., 170 cm),
    but how much it varies - the spread. That variation
    is usually what's important in statistical models
  - Why remove the bias (mean)?
    Because in many models, the absolute location 
    of your data (the mean) is not informative,
    but the variation (spread, direciton, correlation) is
  - Why do we want to do this?
    - Removing thebias (mean) makes your analysis
      robust to global shifts or offsets, so you
      only measure the meaningful differences
    - In the context of logits and softmax, only
      the differencs between logits matter,
      not their absolute values, so mean-centering
      (or similar operations) ensures your analysis
      reflects what actually affects the outcome
  Summary:
  Mean-centering removes irrelevant global shifts
  and lets you focus on the meaningful differences
  between values
- Here, subtracting the average of "mine" and "theirs"
  from "empty" does the same: it focuses on
  how "empty" stands out compared to the alternatives,
  not just its raw value

Summary:
Centering the "empty" logit relative to the
other two makes the indicator robust to shifts in
all logits and ensures it truly measures
"empty vs not empty," jnot just the raw "empty" scores
"""

# %%

"""
Exercise - define your probe directions

Define the tensors `blank_probe` and `my_prob`,
which point in the two directions given above

<details>
<summary>Help - I'm confused by exactly how to take the linear combination here</summary>
Your `linear_probe` tensor has shape `[d_model, row, col, options]`,
where the options are `(blank, theirs, mine)` respectively.
You want to create 2 new tensors of shape `[d_model, row, col]`
where each one is the probe
</details>
"""

# blank(0) - (theirs(1) + mine(2))/2
blank_probe = linear_probe[..., 0] - (linear_probe[..., 1] + linear_probe[..., 2])/2
# mine(2) - theirs(1)
my_probe = linear_probe[..., 2] - linear_probe[..., 1]

tests.test_my_probes(blank_probe, my_probe, linear_probe)

# %%

"""
Now that we've got our probe working, let's see it in action!
We'll take the 20th move in the 0th game as our example:
"""

game_index = 0
move = 20

# Plot board state
utils.plot_board_values(
  focus_states[game_index, move],
  title="Focus game states",
  width=400,
  height=400,
  text=focus_legal_moves_annotation[game_index][move],
)

# Plot model predictions
logprobs = t.full(size=(8, 8), fill_value=-13.0, device=device)
logprobs.flatten()[ALL_SQUARES] = focus_logits[game_index, move].log_softmax(dim=-1)[1:]
utils.plot_board_values(logprobs, title=f"Logprobs after move {move}", width=450, height=400)

"""
Personal note:
We use `log_softmax` instead of `softmax` because:
- Numerical stability: `log_softmax` is more
  numerically stable, especially when dealing with
  very large or very small logits. it avoids
  potential overflow/underflow issues that can
  happen with `exp` in `softmax`
- Interpretability: The output of `log_softmax`
  is the log-probability for each class.
  Log-probabilities are often easier to work
  with mathematically (e.g., for loss functions
  like cross-entropy, or for adding probabilities
  in log-space)
- Consistency: Many downstream tasks (like
  loss computation or log-likelihood analysis
  expect log-probabilities, not probabilities)

In your code, `logprobs` stores the log-probabilities
for each move, which is standard practice in deep learning
for both stability and convenience. If you need
actual probabilities, you can always exponentiate
the log-probs: `probs = logprobs.exp()`
"""

"""
Now, how does the game state (i.e. which moves are legal
for white) change when `F4` is flipped
black to white?

<details>
<summary>Hint</summary>
One move becomes legal, one becomes illegal
</details>

<details>
<summary>Answer</summary>
- `G4` becomes illegal, because you're no longer
  surrounding the vertical line of black pieces
  in column 4
- `D2` becomes legal, because now you'd be
  diagonally surrounding the single black piece
  at `E3`.
</details>

Let's verify this using the `OthelloBoardState` class
"""

cell_r = 5
cell_c = 4
print(f"Flipping the color of cell {'ABCDEFGH'[cell_r]}{cell_c}")

board = utils.OthelloBoardState()
board.update(focus_games_square[game_index, : move + 1].tolist())
valid_moves = board.get_valid_moves()
flipped_board = copy.deepcopy(board)
flipped_board.state[cell_r, cell_c] *= -1
flipped_legal_moves = flipped_board.get_valid_moves()

newly_legal = [utils.square_to_label(move) for move in flipped_legal_moves if move not in valid_moves]
newly_illegal = [utils.square_to_label(move) for move in valid_moves if move not in flipped_legal_moves]
print("newly_legal", newly_legal)
print("newly_illegal", newly_illegal)

"""
We can now intervene on the model's residual stream
using the "my colour vs their colour" direction.
I get the best results intervening after layer 4.
This is a linear intervention - we are just
changing a single dimension of the residual
stream and keeping the others unchanged.
This is a failry simple intervention,
and it's striking that it works!

I apply the fairly janky technique of taking current corrdinate
in the given direction, negating it, and them
multiply by a hyperparameter called `scale`
(scale between 1 and 8 tends to work best - small
isn't enough and big tends to break things).
I haven't tried hard to optimise this and I'm
sure it can be improved! Eg by repalcing the
model's coordinate by a constant rather than
scaling it. I also haven't dug into the best scale
parameters, or, which ones work best in which contexts,
plasubily different cells have different activation scales
on their world models and need different behavior
"""

# %%

"""
# Exercise - define the `apply_scale` function

Define a function which will take in the residual
stream value and the associated hook point
as arguments, and return a modified version of the
residual stream, in the way described above

To be clear, if we define $\vec{v}$ as the probe's
flip direction for a given square (called `flip_dir`
below), then we can write our residual
stream (at `pos=20`, whch is the one we're interested in)
as the vector:

$$
\text{resid}_{20} = \alpha \times \vec{v} + \beta \times \vec{w}
$$

where $\vec{w}$ is some vector orthogonal to $v$.
We want to alter the residual stream at this position
to be:

$$
\text{resid}_{20} = -\text{scale} \times \alpha \times \vec{v} + \beta \times \vec{w}

Remember to normalize vector $\vec{v}$!
$$
"""

def apply_scale(
  resid: Float[Tensor, "batch seq d_model"], 
  flip_dir: Float[Tensor, "d_model"], 
  scale: int, 
  pos: int,
) -> Float[Tensor, "batch seq d_model"]:
  """
  Returns a version of the residual stream, 
  modified by the amount `scale` in the
  direction `flip_dir` at the sequence position 
  `pos`, in the way described above.
  """
  flip_dir_normed = flip_dir / flip_dir.norm()

  alpha = resid[0, pos] @ flip_dir_normed
  resid[0, pos] -= (scale + 1) * alpha * flip_dir_normed

  return resid

tests.test_apply_scale(apply_scale)

"""
Personal note:
1. What does "if we define $\vec{v} as the
   probe's flip direction for a given square
   (called `flip_dir` below), then we can write
   our residual stream (at `pos=20`, which is
   the one we're interested in) as the vector:" mean?
   - $\vec{v}$ (or `flip_dir`) is a specific direction
     in the model's activation space (the probe
     direction for a particular square)
   - The residual stream at a given position (here,
     move 20) is a vector in the same space
   - The statement means: we can decompose the
     residual stream at position 20 into two parts
     - One part along the probe direction (`flip_dir`)
     - One part orthogonal (perpendicular) to it
2. Why are we interested at `pos=20`?
   - `pos=20` refers to the 20th move in the game.
3. Why "$\vec{w}$ is some vector orthogonal to $v$?
   - Any vector in space can be decomposed into
     a component along a direction and a component
     orthogonal to it
   - Here, $\vec{w}$ is the part of the residual
     stream that is not captured by the probe
     direction (`flip_dir`)
   - This decomposition is standard in linear algebra:
     $$ 
     \text{resid_stream} = (
      (\text{projection onto } \vec{v}) 
      + (\text{everything else, orthogonal to} \vec{v}
     )
     $$
4. Why `flip_dir = my_probe[:, cell_r, cell_c]`?
   - `my_probe` is a tensor of probe directions 
     for each square
   - `my_probe[:, cell_r, cell_c]` selects
     the probe direction for the square at
     row `cell_r`, column `cell_c`
   - This direction is used to "read out" or
     intervene on the model's representation
     for that specific square

# Summary
- We decompose the residual stream at a specific
  move (e.g., 20) into a part along the
  probe direction for a square and a part
  orthogonal to it
- This helps us interpret or intervene in the
  model's internal representation for that
  square at that move
"""

# %%

"""
Now, you can run the code below to see the output
of your interventions. You should see that the model's
prediction changes, it starts predicting `D2` as legal
and `G4` as illegal.
"""

flip_dir = my_probe[:, cell_r, cell_c]

logprobs_flipped = []
layer = 4
scales = [0, 1, 2, 4, 8, 16]

# Iterate through scales, generate a new facet plot for each possible scale
for scale in scales:
  # Hook function which will perform flipping in the "F4 flip direction"
  def flip_hook(resid: Float[Tensor, "batch seq d_model"], hook: HookPoint):
    return apply_scale(resid, flip_dir, scale, move)

  # Calculate the logits for the board state, with the `flip_hook` intervention (note that we only need to use :move+1
  # as input, because of causal attention)
  flipped_logits = model.run_with_hooks(
    focus_games_id[game_index, : move + 1],
    fwd_hooks=[
      (get_act_name("resid_post", layer), flip_hook),
    ],
  ).log_softmax(dim=-1)[0, move]

  logprobs_flipped_single = t.zeros((64,), dtype=t.float32, device=device) - 10.0
  logprobs_flipped_single[ALL_SQUARES] = flipped_logits.log_softmax(dim=-1)[1:]
  logprobs_flipped.append(logprobs_flipped_single)

flip_state_big = t.stack(logprobs_flipped)
logprobs_repeated = einops.repeat(logprobs.flatten(), "d -> b d", b=6)
color = t.zeros((len(scales), 64)) + 0.2
color[:, utils.to_square(newly_legal)] = 1
color[:, utils.to_square(newly_illegal)] = -1

scatter(
  y=logprobs_repeated,
  x=flip_state_big,
  title=f"Original vs Flipped {utils.square_to_label(8 * cell_r + cell_c)} at Layer {layer}",
  xaxis="Flipped",
  yaxis="Original",
  hover=[f"{r}{c}" for r in "ABCDEFGH" for c in range(8)],
  facet_col=0,
  facet_labels=[f"Translate by {i}x" for i in scales],
  color=color,
  color_name="Newly Legal",
  color_continuous_scale="Geyser",
  width=1400,
)

"""
<details>
<summary>Help - I'm still confused about this figure / this methodology</summary>
When we mean "translating by `Nx`" for a scalar `N`,
we mean "taking the component `x` of the residual stream
in the `theirs - mine` probe direction for the
F4 square, and replacing it with `Nx`.

The scatter plots compare `-1x` (original)
to `Nx` (flipped) for different values of `x`.
For instance, the first face plot shows what happens
when the residual stream's component in the probe
direction is erased

The fact that we see the model's prediction
for `G4` and `D2` change (with `G4` "becoming more illegal"
and `D2` "becoming more legal") as our scale
factor increases (without significant change
in the predictions for other squares, at first)
is evidence that our causal intervention is valid.
In other words, the direction found by our
linear probe `my_probe` does in some sense represent
the model's `theirs - mine` direction, and this
direction is used by the model downstream.
</details>
"""
# %%
