# i would like to introduce one evaluation that we are going to use to supplement the validation set
# and that is HellaSwag eval
# "HelloSwag: Can a Machine Really Finish Your Sentence?"
# it comes from this paper back in 2019, so it's 5 year old eval now
# the way HellaSwag works is there is basically a sentence completion data set
# so it's a multipel choice for every one of these questions we have basically a shared context
# like
# A woman is outside with a bucket and a dog. The dog is running around trying to avoid a bath. She...
# A. rinses the bucket off with soap and blow dry the dog's head
# B. uses a hose to keep it from getting soapy.
# C. gets the dog wet, then it runs away again. <- correct answer
# D. gets into a bath tub with the dog.
# these multiple choice are constructed so that one of them is a natural continuation of the sentence
# and the others are not
# and the others might not make sense
# so what happens is that models that are not trained very well
# are not able to tell these aparts but models tht have alot of world knowledge
# and can tell a lot about the world wil lbe able to create these completions
# and these sentences are seourced from activity net and wikihow
#and at the bottom of the paper there's kind of like cool chart of the kinds of domains in Wiki house
# there's lots of sentence from computer and electronics, and homes and gardens
# and it has kind of a broad coverage of the kinds of things you need to know about the world
# in order to find the most likely completion
# and the identity of that completion
# one more thing that kind of interesting about hellaswag is the way it was constructed
# is that the incorrect options are deliberately
# adversarially sourced
# so they are not just random sentences, they are actually generated by language models
# they are generated in such a way that language models basically find them difficult but human find them easy
# so they mentioned that humans have a 95% accuracy on this set but at the time the state-of-the-art language model only 48% accuracy
# so at the time this was a good benchmark
# the thing to point though is that this is 5 years ago and since then what happened to hellaswag
# totally just solved. so now the language models are 96% so basically the last 4% is probably error in the data set
# or the questions is really really hard
#
# the reason people like hellaswag is because hellaswag is a smooth eval
# it is an eval that offers quote and unquote early signal
# so early signal means that even small language are going to start at the random chance at 20%
# but they are going to slowly improve and you're going to see 25, 26, 27 etc
# and you can see slow improvement even when the models are very small and its very early
# so it's smooth, it has early signal and it's been around for a long time so that's why kind of like this eval
# 
# now the way that we're going to evlauate this is as follows
# as mentioned we have a shared context and this is kind of like a multiple choice task
# but instead of giving the model a multiple choice question asking it for A, B, C, D
# we can't do that because these models when they are so small are we seeing here
# the models can't do multiple choice they don't understand the concept of associating a label to one of the options of multiple choice
# so we have to give to them in a native form, and the native form is a token completion
# so here's what we do, we construct a batch of 4 rows and T tokens, whatever what T happens to be
# then the shared context that is basically the context for the 4 choices, the tokens of that are shared across all of the rows
# and then we have the 4 options so we kind of lay them out and only one of the optionsi scorrect in this case label 3 option 3
# and so this is the correct option and option 1, 2, and 4 is incorrect
# now these options might be of different lengths so what we do is we sort of like take the longest length
# that the size of the batch B by T and some of these are going to be padded dimensions so they are going unused
# and so we need the tokens we need the correct label and we need a mask
# that tells us which tokens are active and the mask is then zero for these padded areas
# so that how we construct these batches and then in order to predict A B C D
# the way this works we are going to look at the tokens and their probabilities and we're going to pick the option that
# gets the lowest or the highest average probability for the token because that is the most likely completion according to
# the language model, so we're just going to look at the probabilities here and average them up
# across the options and pick the one with the highest probability, roughly speaking.
# you should note that some of the other evals where you might see HellaSwag
# may not do it this way, the may do it in a multiple choice format where you give the context a single and the 4 completions
# and the model is able to see all the four option before it picks the best possible option
# and that's actually an easier task for a model because you get to see the other options when you are picking your choice
# but unfortunately model at our size can't do that, only models at a bigger size are able to do that
# and so our mdoels are slightly handicapped in this way that they are not going to see the other options
# they are only going to see one option at a time and they just have to assign probabilities and the correct option
# has to win out in this metric.
"""
Downloads and evaluates HellaSwag in Python.
https://github.com/rowanz/hellaswag

Example HellaSwag json item:

{"ind": 24, "activity_label": "Roof shingle removal", "ctx_a": "A man is sitting on a roof.", "ctx_b": "he", "ctx": "A man is sitting on a roof. he", "split": "val", "split_type": "indomain", "label": 3, "endings": ["is using wrap to wrap a pair of skis.", "is ripping level tiles off.", "is holding a rubik's cube.", "starts pulling up roofing on a roof."], "source_id": "activitynet~v_-JhWjGDPHMY"}

ind: dataset ID
activity_label: The ActivityNet or WikiHow label for this example
context: There are two formats. The full context is in ctx. When the context ends in an (incomplete) noun phrase, like for ActivityNet, this incomplete noun phrase is in ctx_b, and the context up until then is in ctx_a. This can be useful for models such as BERT that need the last sentence to be complete. However, it's never required. If ctx_b is nonempty, then ctx is the same thing as ctx_a, followed by a space, then ctx_b.
endings: a list of 4 endings. The correct index is given by label (0,1,2, or 3)
split: train, val, or test.
split_type: indomain if the activity label is seen during training, else zeroshot
source_id: Which video or WikiHow article this example came from

gpt2 (124M)
- eleuther harness reports acc 28.92%, acc_norm 31.14% (multiple choice style)
- this script: 10042 acc: 0.2859 acc_norm: 0.2955 (completion style)

gpt2-xl (1558M)
- eleuther harness reports acc 40.04%, acc_norm 50.89% (multiple choice style)
- this script: 10042 acc: 0.3842 acc_norm: 0.4893 (completion style)

The validation set of HellaSwag has a total of 10,042 examples.
"""

import os
import json
import requests
import tiktoken
from tqdm import tqdm
import torch
import torch.nn as nn
from torch.nn import functional as F
from transformers import GPT2LMHeadModel

# -----------------------------------------------------------------------------
DATA_CACHE_DIR = os.path.join(os.path.dirname(__file__), "hellaswag")

def download_file(url: str, fname: str, chunk_size=1024):
  """Helper function to download a file from a given url"""
  resp = requests.get(url, stream=True)
  total = int(resp.headers.get("content-length", 0))
  with open(fname, "wb") as file, tqdm(
    desc=fname,
    total=total,
    unit="iB",
    unit_scale=True,
    unit_divisor=1024,
  ) as bar:
    for data in resp.iter_content(chunk_size=chunk_size):
      size = file.write(data)
      bar.update(size)

hellaswags = {
  "train": "https://raw.githubusercontent.com/rowanz/hellaswag/master/data/hellaswag_train.jsonl",
  "val": "https://raw.githubusercontent.com/rowanz/hellaswag/master/data/hellaswag_val.jsonl",
  "test": "https://raw.githubusercontent.com/rowanz/hellaswag/master/data/hellaswag_test.jsonl",
}

enc = tiktoken.get_encoding("gpt2")

def download(split):
  """Downloads HellaSwag DATA_CACHE_DIR"""
  os.makedirs(DATA_CACHE_DIR, exist_ok=True)
  data_url = hellaswags[split]
  data_filename = os.path.join(DATA_CACHE_DIR, f"hellaswag_{split}.jsonl")
  if not os.path.exists(data_filename):
    print(f"Downloading {data_url} to {data_filename}...")
    download_file(data_url, data_filename)

def render_example(example):
  """
  Given the example as a dictionary, render it as three torch tensors:
  - tokens (the tokens of context + completion, of size 4xN, as there are always 4 candidates)
  - mask (is 1 in the region of the candidate completion, where we evaluate likelihoods)
  - label (the index of the correct completion, which we hope has the highest likelihood)
  """
  ctx = example["ctx"]
  label = example["label"]
  endings = example["endings"]

  # data needed to reproduce this eval on the C size
  data = {
    "label": label,
    "ctx_tokens": None,
    "ending_tokens": [],
  }

  # gather up all the tokens
  ctx_tokens = enc.encode(ctx)
  data["ctx_tokens"] = ctx_tokens
  tok_rows = []
  mask_rows = []
  for end in endings:
    end_tokens = enc.encode(" " + end) # note: prepending " " because GPT-2 tokenizer
    tok_rows.append(ctx_tokens + end_tokens)
    mask_rows.append([0]*len(ctx_tokens) + [1]*len(end_tokens))
    data["ending_tokens"].append(end_tokens)

  # have to be careful during the collation because the number of tokens in each row can differ
  max_len = max(len(row) for row in tok_rows)
  tokens = torch.zeros((4, max_len), dtype=torch.long)
  mask = torch.zeros((4, max_len), dtype=torch.long)
  for i, (tok_row, mask_row) in enumerate(zip(tok_rows, mask_rows)):
    tokens[i, :len(tok_row)] = torch.tensor(tok_row)
    mask[i, :len(mask_row)] = torch.tensor(mask_row)

  return data, tokens, mask, label

def iterate_examples(split):
  # there are 10,042 examples in total in val
  download(split)
  with open(os.path.join(DATA_CACHE_DIR, f"hellaswag_{split}.jsonl"), "r") as f:
    for line in f:
      example = json.loads(line)
      yield example

@torch.no_grad()
def evaluate(model_type: str, device: str):

  torch.set_float32_matmul_precision('high') # use tf32
  model = GPT2LMHeadModel.from_pretrained(model_type)
  model.to(device)
  # model = torch.compile(model) # optionally torch compile the model

  num_correct_norm = 0
  num_correct = 0
  num_total = 0
  for example in iterate_examples("val"):
    data, tokens, mask, label = render_example(example)
    tokens = tokens.to(device)
    mask = mask.to(device)

    # get the logits
    logits = model(tokens).logits
    # evaluate the autoregressive loss at all positions
    shift_logits = (logits[..., :-1, :]).contiguous()
    shift_tokens = (tokens[..., 1:]).contiguous()
    flat_shift_logits = shift_logits.view(-1, shift_logits.size(-1))
    flat_shift_tokens = shift_tokens.view(-1)
    shift_losses = F.cross_entropy(flat_shift_logits, flat_shift_tokens, reduction='none')
    shift_losses = shift_losses.view(tokens.size(0), -1)
    # now get the average loss just for the completion region (where mask == 1), in each row
    shift_mask = (mask[..., 1:]).contiguous() # we must shift mask, so we start at the last prompt token
    masked_shift_losses = shift_losses * shift_mask
    # sum and divide by the number of 1s in the mask
    sum_loss = masked_shift_losses.sum(dim=1)
    avg_loss = sum_loss / shift_mask.sum(dim=1)
    # now we have a loss for each of the 4 completions
    # the one with the lowest loss should be the most likely
    pred = sum_loss.argmin().item()
    pred_norm = avg_loss.argmin().item()

    # accumulate stats
    num_total += 1
    num_correct += int(pred == label)
    num_correct_norm += int(pred_norm == label)
    print(f"{num_total} acc_norm: {num_correct_norm}/{num_total}={num_correct_norm/num_total:.4f}")

    # debug: pretty print a few examples, and the losses in each case
    if num_total < 10:
      print("---")
      print(f"Context:\n {example['ctx']}")
      print(f"Endings:")
      for i, end in enumerate(example["endings"]):
        print(f"{i} (loss: {avg_loss[i].item():.4f}) {end}")
      print(f"predicted: {pred_norm}, actual: {label}")

if __name__ == "__main__":
  import argparse
  parser = argparse.ArgumentParser()
  parser.add_argument("-m", "--model_type", type=str, default="gpt2", help="the model type to use")
  parser.add_argument("-d", "--device", type=str, default="cuda", help="the device to use")
  args = parser.parse_args()
  evaluate(args.model_type, args.device)